### ISSUE TITLE
Import Error 'event_menu_url cannot be empty' Zabbix 4.4.0

### ISSUE THREAD

**Issue by mRiston** [signl4/signl4-integration-zabbix#1]
When trying to import zabbix-signl4.xml into Media Types per readme.md, running Zabbix 4.4.0, the import fails, citing:
`Details Import failed
Incorrect value for field "event_menu_url": cannot be empty.`

**Comment by mRiston** [comment]
I got this working by adding a <show_event_menu> element. Added to pull request #2 

`<?xml version="1.0" encoding="UTF-8"?>
<zabbix_export>
    <version>4.4</version>
    <date>2020-01-29T12:59:01Z</date>
    <media_types>
        <media_type>
[...]
            <show_event_menu>NO</show_event_menu>
[...]
        </media_type>
    </media_types>
	
</zabbix_export>
`

**Comment by rons4** [comment]
Thanks a lot @mRiston and sorry for my late reply. I just merged your Pull Request.
